### ISSUE TITLE
Top professionals should be a filter and not a tab

### ISSUE THREAD

**Issue by BonganiBmG** [BaseSpaceCode/klipa-gig#9]
Top professionals should be a filter and not an actual page. 
Either rename as professionals than 'top' professionals.
<img width="1174" alt="Screenshot 2022-11-17 at 15 19 36" src="https://user-images.githubusercontent.com/58253154/202457623-848d6ea7-323a-406f-bb49-5709653308b6.png">

**Comment by BaseSpaceCode** [comment]
![1](https://user-images.githubusercontent.com/96106271/202524303-01fe9d9d-d3f5-400f-afc0-174742276495.png)
 
Completed
